USE INVOICEDM;
GO

-- DESCRIPTION: GENERATE ARGB COLOR VALUE
-- =============================================
IF OBJECT_ID (N'DBO.GETRGB', N'FN') IS NOT NULL  
    DROP FUNCTION DBO.GETRGB;  
GO  
CREATE FUNCTION DBO.GETRGB(@INTALPHA TINYINT, @INTRED  TINYINT, @INTGREEN TINYINT, @INTBLUE TINYINT) RETURNS INT
AS
BEGIN
    DECLARE @LNGCOLOR BIGINT;
    DECLARE @INTCOLOR INT;
    -- GENERATE THE COLOR
    SET @LNGCOLOR = (
        (CAST(@INTALPHA AS BIGINT) * 16777216) +
        (CAST(@INTRED AS BIGINT) * 65536) +
        (CAST(@INTGREEN AS BIGINT) * 256)  +
        (CAST(@INTBLUE AS BIGINT))
    );
    -- GET THE COLOR
    SET @INTCOLOR = CAST(CAST(@LNGCOLOR AS BINARY(4)) AS INT);
    -- RETURN THE COLOR
    RETURN @INTCOLOR;
END