USE [InvoiceDM];
GO

IF OBJECT_ID (N'dbo.NVL', N'FN') IS NOT NULL  
    DROP FUNCTION dbo.NVL;  
GO

CREATE FUNCTION dbo.NVL(@valIn AS NVARCHAR(200), @valOut NVARCHAR(200)) RETURNS NVARCHAR(200)
AS
BEGIN
	DECLARE @STR NVARCHAR(200);
	SET @STR = IIF(@valIn IS NULL, @valOut, @valIn);
	RETURN @STR;
END;